// This file is auto-generated by scripts/generate-decision-models.ts
// Do not edit manually - run 'npm run generate-decision-models' to update

import type { DecisionModel } from "./decision-models.ts";

export const DECISION_MODELS: readonly DecisionModel[] = [
	{
		provider: "cloudflare-ai-gateway",
		id: "typesafe/jev",
		name: "Jev",
		contextWindow: 32000,
		cost: { input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	{
		provider: "nano-gpt",
		id: "typesafe/jev-latest",
		name: "Jev Latest",
		contextWindow: 32000,
		cost: { input: 0.042, output: 0, cacheRead: 0.021, cacheWrite: 0 },
	},
	{
		provider: "opencode",
		id: "jev-1.13",
		name: "Jev 1.13",
		contextWindow: 64000,
		cost: { input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	{
		provider: "opencode",
		id: "jev-1.13-free",
		name: "Jev 1.13 Free",
		contextWindow: 64000,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	{
		provider: "vercel",
		id: "typesafe-ai/jev",
		name: "Jev",
		contextWindow: 32000,
		cost: { input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	{
		provider: "vivgrid",
		id: "jev",
		name: "Jev",
		contextWindow: 64000,
		cost: { input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
];
