// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file cursor-catalog.proto (package agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cursor-catalog.proto.
 */
export const file_cursor_catalog: GenFile = /*@__PURE__*/
  fileDesc("ChRjdXJzb3ItY2F0YWxvZy5wcm90bxIIYWdlbnQudjEiGAoWR2V0VXNhYmxlTW9kZWxzUmVxdWVzdCJBChdHZXRVc2FibGVNb2RlbHNSZXNwb25zZRImCgZtb2RlbHMYASADKAsyFi5hZ2VudC52MS5Nb2RlbERldGFpbHMikAEKDE1vZGVsRGV0YWlscxIQCghtb2RlbF9pZBgBIAEoCRIYChBkaXNwbGF5X21vZGVsX2lkGAMgASgJEhQKDGRpc3BsYXlfbmFtZRgEIAEoCRIaChJkaXNwbGF5X25hbWVfc2hvcnQYBSABKAkSFQoIbWF4X21vZGUYByABKAhIAIgBAUILCglfbWF4X21vZGUijQEKDlJlcXVlc3RlZE1vZGVsEhAKCG1vZGVsX2lkGAEgASgJEhAKCG1heF9tb2RlGAIgASgIEkAKCnBhcmFtZXRlcnMYAyADKAsyLC5hZ2VudC52MS5SZXF1ZXN0ZWRNb2RlbC5Nb2RlbFBhcmFtZXRlcmJ5dGVzGhUKE01vZGVsUGFyYW1ldGVyYnl0ZXNiBnByb3RvMw");

/**
 * Purpose-minimal catalog and route identity schema retained from the checked-in
 * Cursor descriptor baseline documented in README.md.
 *
 * @generated from message agent.v1.GetUsableModelsRequest
 */
export type GetUsableModelsRequest = Message<"agent.v1.GetUsableModelsRequest"> & {
};

/**
 * Describes the message agent.v1.GetUsableModelsRequest.
 * Use `create(GetUsableModelsRequestSchema)` to create a new message.
 */
export const GetUsableModelsRequestSchema: GenMessage<GetUsableModelsRequest> = /*@__PURE__*/
  messageDesc(file_cursor_catalog, 0);

/**
 * @generated from message agent.v1.GetUsableModelsResponse
 */
export type GetUsableModelsResponse = Message<"agent.v1.GetUsableModelsResponse"> & {
  /**
   * @generated from field: repeated agent.v1.ModelDetails models = 1;
   */
  models: ModelDetails[];
};

/**
 * Describes the message agent.v1.GetUsableModelsResponse.
 * Use `create(GetUsableModelsResponseSchema)` to create a new message.
 */
export const GetUsableModelsResponseSchema: GenMessage<GetUsableModelsResponse> = /*@__PURE__*/
  messageDesc(file_cursor_catalog, 1);

/**
 * @generated from message agent.v1.ModelDetails
 */
export type ModelDetails = Message<"agent.v1.ModelDetails"> & {
  /**
   * @generated from field: string model_id = 1;
   */
  modelId: string;

  /**
   * @generated from field: string display_model_id = 3;
   */
  displayModelId: string;

  /**
   * @generated from field: string display_name = 4;
   */
  displayName: string;

  /**
   * @generated from field: string display_name_short = 5;
   */
  displayNameShort: string;

  /**
   * @generated from field: optional bool max_mode = 7;
   */
  maxMode?: boolean | undefined;
};

/**
 * Describes the message agent.v1.ModelDetails.
 * Use `create(ModelDetailsSchema)` to create a new message.
 */
export const ModelDetailsSchema: GenMessage<ModelDetails> = /*@__PURE__*/
  messageDesc(file_cursor_catalog, 2);

/**
 * @generated from message agent.v1.RequestedModel
 */
export type RequestedModel = Message<"agent.v1.RequestedModel"> & {
  /**
   * @generated from field: string model_id = 1;
   */
  modelId: string;

  /**
   * @generated from field: bool max_mode = 2;
   */
  maxMode: boolean;

  /**
   * @generated from field: repeated agent.v1.RequestedModel.ModelParameterbytes parameters = 3;
   */
  parameters: RequestedModel_ModelParameterbytes[];
};

/**
 * Describes the message agent.v1.RequestedModel.
 * Use `create(RequestedModelSchema)` to create a new message.
 */
export const RequestedModelSchema: GenMessage<RequestedModel> = /*@__PURE__*/
  messageDesc(file_cursor_catalog, 3);

/**
 * @generated from message agent.v1.RequestedModel.ModelParameterbytes
 */
export type RequestedModel_ModelParameterbytes = Message<"agent.v1.RequestedModel.ModelParameterbytes"> & {
};

/**
 * Describes the message agent.v1.RequestedModel.ModelParameterbytes.
 * Use `create(RequestedModel_ModelParameterbytesSchema)` to create a new message.
 */
export const RequestedModel_ModelParameterbytesSchema: GenMessage<RequestedModel_ModelParameterbytes> = /*@__PURE__*/
  messageDesc(file_cursor_catalog, 3, 0);
