#!/usr/bin/env node

import { writeFileSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";
import type { DecisionModel } from "../src/decision-models.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

// The default models.dev catalog omits specialized model types; `type=all` includes
// `decision` rows such as TypeSafe Jev on the gateways that resell it.
const MODELS_DEV_ALL_TYPES_URL = "https://models.dev/api.json?type=all";

function readStrictOption(args: string[]): boolean {
	for (const arg of args) {
		if (arg !== "--strict") throw new Error(`Unknown argument: ${arg}`);
	}
	return args.includes("--strict");
}

interface ModelsDevDecisionRecord {
	id?: string;
	name?: string;
	type?: string;
	limit?: { context?: number; input?: number; output?: number };
	cost?: { input?: number; output?: number; cache_read?: number; cache_write?: number };
}

interface ModelsDevProviderRecord {
	models?: Record<string, ModelsDevDecisionRecord>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function parseModelsDevDecisionModels(payload: unknown, strict: boolean): DecisionModel[] {
	if (!isRecord(payload)) {
		if (strict) throw new Error("models.dev returned a non-object catalog");
		return [];
	}
	const models: DecisionModel[] = [];
	for (const [provider, providerRecord] of Object.entries(payload as Record<string, ModelsDevProviderRecord>)) {
		for (const [modelId, model] of Object.entries(providerRecord.models ?? {})) {
			if (model.type !== "decision") continue;
			const contextWindow = model.limit?.context;
			if (typeof contextWindow !== "number" || contextWindow <= 0) {
				if (strict) throw new Error(`models.dev decision model ${provider}/${modelId} has no context limit`);
				continue;
			}
			models.push({
				provider,
				id: model.id ?? modelId,
				name: model.name ?? modelId,
				contextWindow,
				cost: {
					input: model.cost?.input ?? 0,
					output: model.cost?.output ?? 0,
					cacheRead: model.cost?.cache_read ?? 0,
					cacheWrite: model.cost?.cache_write ?? 0,
				},
			});
		}
	}
	models.sort((a, b) => a.provider.localeCompare(b.provider) || a.id.localeCompare(b.id));
	if (strict && models.length === 0) throw new Error("models.dev returned no decision models");
	return models;
}

async function fetchModelsDevDecisionModels(strict: boolean): Promise<DecisionModel[]> {
	console.log(`Fetching decision models from ${MODELS_DEV_ALL_TYPES_URL}...`);
	const response = await fetch(MODELS_DEV_ALL_TYPES_URL);
	if (!response.ok) throw new Error(`models.dev API returned ${response.status}`);
	return parseModelsDevDecisionModels(await response.json(), strict);
}

export function generateDecisionModelsFile(models: readonly DecisionModel[]): string {
	const rows = models
		.map(
			(model) =>
				`\t{\n\t\tprovider: ${JSON.stringify(model.provider)},\n\t\tid: ${JSON.stringify(model.id)},\n\t\tname: ${JSON.stringify(model.name)},\n\t\tcontextWindow: ${model.contextWindow},\n\t\tcost: { input: ${model.cost.input}, output: ${model.cost.output}, cacheRead: ${model.cost.cacheRead}, cacheWrite: ${model.cost.cacheWrite} },\n\t},`,
		)
		.join("\n");
	return `// This file is auto-generated by scripts/generate-decision-models.ts
// Do not edit manually - run 'npm run generate-decision-models' to update

import type { DecisionModel } from "./decision-models.ts";

export const DECISION_MODELS: readonly DecisionModel[] = [
${rows}
];
`;
}

async function main(): Promise<void> {
	const strict = readStrictOption(process.argv.slice(2));
	const models = await fetchModelsDevDecisionModels(strict);
	const output = generateDecisionModelsFile(models);
	const outputPath = join(packageRoot, "src", "decision-models.generated.ts");
	writeFileSync(outputPath, output, "utf-8");
	console.log(`Generated ${outputPath} (${models.length} decision models)`);
}

if (process.argv[1] && resolve(process.argv[1]) === __filename) {
	main().catch((error) => {
		console.error(error);
		process.exit(1);
	});
}
