import type { ImageContent, TextContent, Usage } from "@bastani/pi-ai/compat";
import type { AgentMessage } from "@earendil-works/pi-agent-core";
import type { SessionManager } from "./session-manager-core.ts";

export const CURRENT_SESSION_VERSION = 3;

/**
 * Workflow linkage persisted on internal (workflow-created) session headers.
 * Used to exclude workflow stage sessions from the standard `/resume` history
 * while keeping them resumable through the workflow-specific resume path.
 */
export interface SessionWorkflowMetadata {
	runId: string;
	stageId: string;
	stageName: string;
}

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
	/** Marks sessions created by automated machinery (e.g. workflow stages) so they can be excluded from standard resume history. */
	internal?: boolean;
	/** When internal, links the session to its owning workflow run/stage. */
	workflow?: SessionWorkflowMetadata;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
	/** Mark the new session as internal (e.g. a workflow stage session). */
	internal?: boolean;
	/** Workflow run/stage linkage for internal workflow sessions. */
	workflow?: SessionWorkflowMetadata;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

/** Durable compaction boundary. Active entries carry `details.strategy === "verbatim-lines"`. */
export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	/** First context-visible tail entry, or null when the durable summary replaces the entire pre-boundary transcript. */
	firstKeptEntryId: string | null;
	tokensBefore: number;
	details?: T;
	/** Aggregate usage from model calls that produced this boundary. */
	usage?: Usage;
	/** True when the compacted text was supplied by an extension hook. */
	fromHook?: boolean;
}

/** @deprecated Legacy archival statistics; never produced or applied. */
export interface ContextCompactionStats {
	objectsBefore: number;
	objectsAfter: number;
	objectsDeleted: number;
	tokensBefore: number;
	tokensAfter: number;
	percentReduction: number;
}

/** @deprecated Legacy archival record; never produced or applied. */
export interface ContextCompactionEntry extends SessionEntryBase {
	type: "context_compaction";
	promptVersion: 1;
	deletedTargets: Array<
		{ kind: "entry"; entryId: string } | { kind: "content_block"; entryId: string; blockIndex: number }
	>;
	protectedEntryIds: string[];
	stats: ContextCompactionStats;
	backupPath?: string;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** Usage from the model call that generated this summary. */
	usage?: Usage;
	/** True if generated by an extension, false if generated by Atomic. */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Session name read state, mirroring pi's has_session_name / session_name pair
 * (upstream 7bdb16c2): the fact that a session was ever named is separate from the
 * name it currently holds. The distinction is already durable in the JSONL — a clear
 * appends a `session_info` entry with an empty name, a never-named session has none —
 * so this is a read-side shape, not a storage change.
 *
 * - `{ hasName: false }` — no `session_info` entry exists; the session was never named.
 * - `{ hasName: true }` — the latest `session_info` entry has an empty name; the session
 *   was named and then cleared.
 * - `{ hasName: true, name: "…" }` — the session currently holds this name.
 */
export interface SessionNameState {
	/** True when a `session_info` entry exists, even if its latest name is empty (cleared). */
	hasName: boolean;
	/** Current name. Undefined for both a cleared and a never-named session. */
	name?: string;
}

/** Session summary metadata entry. */
export interface SessionSummaryEntry extends SessionEntryBase {
	type: "session_summary";
	summary: string;
	summarizedThroughId: string;
	usage?: Usage;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this usually participates in LLM context.
 * The content is converted to a user message in buildSessionContext() unless
 * excludeFromContext is true. Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface ProtectedReconciliationMarker {
	delivery: "steer" | "followUp";
}

export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
	excludeFromContext?: boolean;
	/** Stable producer identity used by workflow stages to de-nominate admitted external turns. */
	stageAdmissionKey?: string;
	/** Runtime provenance used to distinguish stage continuation from an externally triggered response. */
	/** Internal crash-recovery marker for a model-facing protected turn. */
	protectedReconciliation?: ProtectedReconciliationMarker;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| ContextCompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry
	| SessionSummaryEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/**
	 * User-defined display name from session_info entries. Undefined both for a
	 * never-named session and for one whose name was cleared; `hasName` separates them.
	 */
	name?: string;
	/** True when a session_info entry exists, even if the name was later cleared. */
	hasName?: boolean;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	/** True when this session was created by automated machinery (e.g. a workflow stage). */
	internal?: boolean;
	/** Workflow run/stage linkage when the session is an internal workflow session. */
	workflow?: SessionWorkflowMetadata;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	/** Generated resume summary. Absent when never generated, or stale against the latest message. */
	summary?: string;
	allMessagesText: string;
	/** Optional semantic color for synthetic selector rows. */
	messageColor?: "success" | "warning" | "accent" | "error";
}

export type SessionListProgress = (loaded: number, total: number) => void;

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "usesDefaultSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
	| "getSessionNameState"
>;
