import { test } from "bun:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const checkerPath = join(repoRoot, "scripts/check-file-length.ts");

// Build a file body with exactly `count` physical lines. When `trailingNewline`
// is false the final line has no terminating "\n", which exercises the checker's
// trailing-newline correction (a last line without "\n" still counts).
function lines(count: number, trailingNewline = true): string {
  const body = Array.from({ length: count }, (_, index) => `line ${index + 1}`).join("\n");
  return trailingNewline ? `${body}\n` : body;
}

function runChecker(cwd: string, args: string[] = []) {
  return Bun.spawnSync({
    cmd: [process.execPath, checkerPath, ...args],
    cwd,
    stdout: "pipe",
    stderr: "pipe",
  });
}

function withFixture(run: (root: string) => void): void {
  const root = mkdtempSync(join(tmpdir(), "atomic-file-length-"));
  try {
    run(root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

test("passes at the 500-line boundary and fails at 501", () => {
  withFixture((root) => {
    writeFileSync(join(root, "ok.ts"), lines(500));
    const result = runChecker(root);
    assert.equal(result.exitCode, 0, result.stderr.toString());
  });

  withFixture((root) => {
    writeFileSync(join(root, "too-long.ts"), lines(501));
    const result = runChecker(root);
    assert.equal(result.exitCode, 1);
    assert.match(result.stderr.toString(), /too-long\.ts/);
  });
});

test("counts a final line that has no trailing newline", () => {
  // 500 physical lines without a trailing newline is still exactly 500 (passes).
  withFixture((root) => {
    writeFileSync(join(root, "exactly-500.ts"), lines(500, false));
    assert.equal(runChecker(root).exitCode, 0);
  });

  // 501 physical lines without a trailing newline must still be flagged.
  withFixture((root) => {
    writeFileSync(join(root, "no-newline.ts"), lines(501, false));
    const result = runChecker(root);
    assert.equal(result.exitCode, 1);
    assert.match(result.stderr.toString(), /no-newline\.ts/);
  });
});

test("skips files carrying a generated marker in the first lines", () => {
  for (const marker of ["// @generated by protoc", "/* auto-generated */", "// DO NOT EDIT"]) {
    withFixture((root) => {
      writeFileSync(join(root, "generated.ts"), `${marker}\n${lines(600)}`);
      assert.equal(runChecker(root).exitCode, 0, `marker: ${marker}`);
    });
  }
});

test("skips vendored, minified, and impeccable-bundle paths", () => {
  withFixture((root) => {
    writeFileSync(join(root, "bundle.min.js"), lines(600));

    mkdirSync(join(root, "vendor"), { recursive: true });
    writeFileSync(join(root, "vendor/lib.ts"), lines(600));

    mkdirSync(join(root, "packages/workflows/skills/impeccable/scripts"), { recursive: true });
    writeFileSync(join(root, "packages/workflows/skills/impeccable/scripts/detector.ts"), lines(600));

    assert.equal(runChecker(root).exitCode, 0, runChecker(root).stderr.toString());
  });
});

test("ignores files without an in-scope extension", () => {
  withFixture((root) => {
    writeFileSync(join(root, "notes.md"), lines(900));
    writeFileSync(join(root, "styles.css"), lines(900));
    assert.equal(runChecker(root).exitCode, 0);
  });
});

test("--max overrides the default limit", () => {
  withFixture((root) => {
    writeFileSync(join(root, "small.ts"), lines(10));
    assert.equal(runChecker(root, ["--max=5"]).exitCode, 1);
    assert.equal(runChecker(root, ["--max=20"]).exitCode, 0);
  });
});

test("rejects an invalid --max value with a usage error", () => {
  withFixture((root) => {
    writeFileSync(join(root, "x.ts"), lines(10));
    const result = runChecker(root, ["--max=abc"]);
    assert.equal(result.exitCode, 2);
    assert.match(result.stderr.toString(), /--max/);
  });
});
