// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/ant-ling.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const ANT_LING_MODELS: ChatModelCatalog<typeof import("./data/ant-ling.json", { with: { type: "json" } }), "ant-ling"> =
	flattenChatModelCatalog("ant-ling", values);

export const ANT_LING_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/ant-ling.json", { with: { type: "json" } }), "ant-ling"> =
	flattenImageModelCatalog("ant-ling", values);

export const ANT_LING_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/ant-ling.json", { with: { type: "json" } }), "ant-ling"> =
	flattenClassifierModelCatalog("ant-ling", values);
