// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/anthropic.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const ANTHROPIC_MODELS: ChatModelCatalog<typeof import("./data/anthropic.json", { with: { type: "json" } }), "anthropic"> =
	flattenChatModelCatalog("anthropic", values);

export const ANTHROPIC_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/anthropic.json", { with: { type: "json" } }), "anthropic"> =
	flattenImageModelCatalog("anthropic", values);

export const ANTHROPIC_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/anthropic.json", { with: { type: "json" } }), "anthropic"> =
	flattenClassifierModelCatalog("anthropic", values);
