// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/azure.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const AZURE_MODELS: ChatModelCatalog<typeof import("./data/azure.json", { with: { type: "json" } }), "azure"> =
	flattenChatModelCatalog("azure", values);

export const AZURE_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/azure.json", { with: { type: "json" } }), "azure"> =
	flattenImageModelCatalog("azure", values);

export const AZURE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/azure.json", { with: { type: "json" } }), "azure"> =
	flattenClassifierModelCatalog("azure", values);
