// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

/** @deprecated Use the Azure catalogs from providers/azure.models. */
export {
	AZURE_MODELS as AZURE_OPENAI_RESPONSES_MODELS,
	AZURE_IMAGE_MODELS as AZURE_OPENAI_RESPONSES_IMAGE_MODELS,
	AZURE_CLASSIFIER_MODELS as AZURE_OPENAI_RESPONSES_CLASSIFIER_MODELS,
} from "./azure.models.ts";
