// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/azure-openai-responses.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const AZURE_OPENAI_RESPONSES_MODELS: ChatModelCatalog<typeof import("./data/azure-openai-responses.json", { with: { type: "json" } }), "azure-openai-responses"> =
	flattenChatModelCatalog("azure-openai-responses", values);

export const AZURE_OPENAI_RESPONSES_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/azure-openai-responses.json", { with: { type: "json" } }), "azure-openai-responses"> =
	flattenImageModelCatalog("azure-openai-responses", values);

export const AZURE_OPENAI_RESPONSES_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/azure-openai-responses.json", { with: { type: "json" } }), "azure-openai-responses"> =
	flattenClassifierModelCatalog("azure-openai-responses", values);
