// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cerebras.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const CEREBRAS_MODELS: ChatModelCatalog<typeof import("./data/cerebras.json", { with: { type: "json" } }), "cerebras"> =
	flattenChatModelCatalog("cerebras", values);

export const CEREBRAS_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/cerebras.json", { with: { type: "json" } }), "cerebras"> =
	flattenImageModelCatalog("cerebras", values);

export const CEREBRAS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/cerebras.json", { with: { type: "json" } }), "cerebras"> =
	flattenClassifierModelCatalog("cerebras", values);
