// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepseek.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const DEEPSEEK_MODELS: ChatModelCatalog<typeof import("./data/deepseek.json", { with: { type: "json" } }), "deepseek"> =
	flattenChatModelCatalog("deepseek", values);

export const DEEPSEEK_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/deepseek.json", { with: { type: "json" } }), "deepseek"> =
	flattenImageModelCatalog("deepseek", values);

export const DEEPSEEK_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/deepseek.json", { with: { type: "json" } }), "deepseek"> =
	flattenClassifierModelCatalog("deepseek", values);
