// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/fireworks.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const FIREWORKS_MODELS: ChatModelCatalog<typeof import("./data/fireworks.json", { with: { type: "json" } }), "fireworks"> =
	flattenChatModelCatalog("fireworks", values);

export const FIREWORKS_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/fireworks.json", { with: { type: "json" } }), "fireworks"> =
	flattenImageModelCatalog("fireworks", values);

export const FIREWORKS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/fireworks.json", { with: { type: "json" } }), "fireworks"> =
	flattenClassifierModelCatalog("fireworks", values);
