// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/google.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const GOOGLE_MODELS: ChatModelCatalog<typeof import("./data/google.json", { with: { type: "json" } }), "google"> =
	flattenChatModelCatalog("google", values);

export const GOOGLE_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/google.json", { with: { type: "json" } }), "google"> =
	flattenImageModelCatalog("google", values);

export const GOOGLE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/google.json", { with: { type: "json" } }), "google"> =
	flattenClassifierModelCatalog("google", values);
