// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/groq.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const GROQ_MODELS: ChatModelCatalog<typeof import("./data/groq.json", { with: { type: "json" } }), "groq"> =
	flattenChatModelCatalog("groq", values);

export const GROQ_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/groq.json", { with: { type: "json" } }), "groq"> =
	flattenImageModelCatalog("groq", values);

export const GROQ_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/groq.json", { with: { type: "json" } }), "groq"> =
	flattenClassifierModelCatalog("groq", values);
