// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/huggingface.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const HUGGINGFACE_MODELS: ChatModelCatalog<typeof import("./data/huggingface.json", { with: { type: "json" } }), "huggingface"> =
	flattenChatModelCatalog("huggingface", values);

export const HUGGINGFACE_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/huggingface.json", { with: { type: "json" } }), "huggingface"> =
	flattenImageModelCatalog("huggingface", values);

export const HUGGINGFACE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/huggingface.json", { with: { type: "json" } }), "huggingface"> =
	flattenClassifierModelCatalog("huggingface", values);
