// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/kimi-coding.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const KIMI_CODING_MODELS: ChatModelCatalog<typeof import("./data/kimi-coding.json", { with: { type: "json" } }), "kimi-coding"> =
	flattenChatModelCatalog("kimi-coding", values);

export const KIMI_CODING_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/kimi-coding.json", { with: { type: "json" } }), "kimi-coding"> =
	flattenImageModelCatalog("kimi-coding", values);

export const KIMI_CODING_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/kimi-coding.json", { with: { type: "json" } }), "kimi-coding"> =
	flattenClassifierModelCatalog("kimi-coding", values);
