// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/nvidia.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const NVIDIA_MODELS: ChatModelCatalog<typeof import("./data/nvidia.json", { with: { type: "json" } }), "nvidia"> =
	flattenChatModelCatalog("nvidia", values);

export const NVIDIA_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/nvidia.json", { with: { type: "json" } }), "nvidia"> =
	flattenImageModelCatalog("nvidia", values);

export const NVIDIA_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/nvidia.json", { with: { type: "json" } }), "nvidia"> =
	flattenClassifierModelCatalog("nvidia", values);
