// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/opencode-go.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const OPENCODE_GO_MODELS: ChatModelCatalog<typeof import("./data/opencode-go.json", { with: { type: "json" } }), "opencode-go"> =
	flattenChatModelCatalog("opencode-go", values);

export const OPENCODE_GO_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/opencode-go.json", { with: { type: "json" } }), "opencode-go"> =
	flattenImageModelCatalog("opencode-go", values);

export const OPENCODE_GO_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/opencode-go.json", { with: { type: "json" } }), "opencode-go"> =
	flattenClassifierModelCatalog("opencode-go", values);
