// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openai-images.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const OPENAI_IMAGES_MODELS: ChatModelCatalog<typeof import("./data/openai-images.json", { with: { type: "json" } }), "openai-images"> =
	flattenChatModelCatalog("openai-images", values);

export const OPENAI_IMAGES_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/openai-images.json", { with: { type: "json" } }), "openai-images"> =
	flattenImageModelCatalog("openai-images", values);

export const OPENAI_IMAGES_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/openai-images.json", { with: { type: "json" } }), "openai-images"> =
	flattenClassifierModelCatalog("openai-images", values);
