// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const OPENAI_MODELS: ChatModelCatalog<typeof import("./data/openai.json", { with: { type: "json" } }), "openai"> =
	flattenChatModelCatalog("openai", values);

export const OPENAI_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/openai.json", { with: { type: "json" } }), "openai"> =
	flattenImageModelCatalog("openai", values);

export const OPENAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/openai.json", { with: { type: "json" } }), "openai"> =
	flattenClassifierModelCatalog("openai", values);
