// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openai-codex.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const OPENAI_CODEX_MODELS: ChatModelCatalog<typeof import("./data/openai-codex.json", { with: { type: "json" } }), "openai-codex"> =
	flattenChatModelCatalog("openai-codex", values);

export const OPENAI_CODEX_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/openai-codex.json", { with: { type: "json" } }), "openai-codex"> =
	flattenImageModelCatalog("openai-codex", values);

export const OPENAI_CODEX_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/openai-codex.json", { with: { type: "json" } }), "openai-codex"> =
	flattenClassifierModelCatalog("openai-codex", values);
