// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openrouter.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const OPENROUTER_MODELS: ChatModelCatalog<typeof import("./data/openrouter.json", { with: { type: "json" } }), "openrouter"> =
	flattenChatModelCatalog("openrouter", values);

export const OPENROUTER_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/openrouter.json", { with: { type: "json" } }), "openrouter"> =
	flattenImageModelCatalog("openrouter", values);

export const OPENROUTER_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/openrouter.json", { with: { type: "json" } }), "openrouter"> =
	flattenClassifierModelCatalog("openrouter", values);
