// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openai-decisions.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const OPENAI_DECISIONS_MODELS: ChatModelCatalog<typeof import("./data/openai-decisions.json", { with: { type: "json" } }), "openai-decisions"> =
	flattenChatModelCatalog("openai-decisions", values);

export const OPENAI_DECISIONS_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/openai-decisions.json", { with: { type: "json" } }), "openai-decisions"> =
	flattenImageModelCatalog("openai-decisions", values);

export const OPENAI_DECISIONS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/openai-decisions.json", { with: { type: "json" } }), "openai-decisions"> =
	flattenClassifierModelCatalog("openai-decisions", values);
