// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen-token-plan.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const QWEN_TOKEN_PLAN_MODELS: ChatModelCatalog<typeof import("./data/qwen-token-plan.json", { with: { type: "json" } }), "qwen-token-plan"> =
	flattenChatModelCatalog("qwen-token-plan", values);

export const QWEN_TOKEN_PLAN_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/qwen-token-plan.json", { with: { type: "json" } }), "qwen-token-plan"> =
	flattenImageModelCatalog("qwen-token-plan", values);

export const QWEN_TOKEN_PLAN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/qwen-token-plan.json", { with: { type: "json" } }), "qwen-token-plan"> =
	flattenClassifierModelCatalog("qwen-token-plan", values);
