// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen-token-plan-cn.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const QWEN_TOKEN_PLAN_CN_MODELS: ChatModelCatalog<typeof import("./data/qwen-token-plan-cn.json", { with: { type: "json" } }), "qwen-token-plan-cn"> =
	flattenChatModelCatalog("qwen-token-plan-cn", values);

export const QWEN_TOKEN_PLAN_CN_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/qwen-token-plan-cn.json", { with: { type: "json" } }), "qwen-token-plan-cn"> =
	flattenImageModelCatalog("qwen-token-plan-cn", values);

export const QWEN_TOKEN_PLAN_CN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/qwen-token-plan-cn.json", { with: { type: "json" } }), "qwen-token-plan-cn"> =
	flattenClassifierModelCatalog("qwen-token-plan-cn", values);
