// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/radius.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const RADIUS_MODELS: ChatModelCatalog<typeof import("./data/radius.json", { with: { type: "json" } }), "radius"> =
	flattenChatModelCatalog("radius", values);

export const RADIUS_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/radius.json", { with: { type: "json" } }), "radius"> =
	flattenImageModelCatalog("radius", values);

export const RADIUS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/radius.json", { with: { type: "json" } }), "radius"> =
	flattenClassifierModelCatalog("radius", values);
