// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/together.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const TOGETHER_MODELS: ChatModelCatalog<typeof import("./data/together.json", { with: { type: "json" } }), "together"> =
	flattenChatModelCatalog("together", values);

export const TOGETHER_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/together.json", { with: { type: "json" } }), "together"> =
	flattenImageModelCatalog("together", values);

export const TOGETHER_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/together.json", { with: { type: "json" } }), "together"> =
	flattenClassifierModelCatalog("together", values);
