// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/typesafe.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const TYPESAFE_MODELS: ChatModelCatalog<typeof import("./data/typesafe.json", { with: { type: "json" } }), "typesafe"> =
	flattenChatModelCatalog("typesafe", values);

export const TYPESAFE_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/typesafe.json", { with: { type: "json" } }), "typesafe"> =
	flattenImageModelCatalog("typesafe", values);

export const TYPESAFE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/typesafe.json", { with: { type: "json" } }), "typesafe"> =
	flattenClassifierModelCatalog("typesafe", values);
