// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const XAI_MODELS: ChatModelCatalog<typeof import("./data/xai.json", { with: { type: "json" } }), "xai"> =
	flattenChatModelCatalog("xai", values);

export const XAI_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/xai.json", { with: { type: "json" } }), "xai"> =
	flattenImageModelCatalog("xai", values);

export const XAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/xai.json", { with: { type: "json" } }), "xai"> =
	flattenClassifierModelCatalog("xai", values);
