// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi-token-plan-ams.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const XIAOMI_TOKEN_PLAN_AMS_MODELS: ChatModelCatalog<typeof import("./data/xiaomi-token-plan-ams.json", { with: { type: "json" } }), "xiaomi-token-plan-ams"> =
	flattenChatModelCatalog("xiaomi-token-plan-ams", values);

export const XIAOMI_TOKEN_PLAN_AMS_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/xiaomi-token-plan-ams.json", { with: { type: "json" } }), "xiaomi-token-plan-ams"> =
	flattenImageModelCatalog("xiaomi-token-plan-ams", values);

export const XIAOMI_TOKEN_PLAN_AMS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/xiaomi-token-plan-ams.json", { with: { type: "json" } }), "xiaomi-token-plan-ams"> =
	flattenClassifierModelCatalog("xiaomi-token-plan-ams", values);
