// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zai-coding-cn.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const ZAI_CODING_CN_MODELS: ChatModelCatalog<typeof import("./data/zai-coding-cn.json", { with: { type: "json" } }), "zai-coding-cn"> =
	flattenChatModelCatalog("zai-coding-cn", values);

export const ZAI_CODING_CN_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/zai-coding-cn.json", { with: { type: "json" } }), "zai-coding-cn"> =
	flattenImageModelCatalog("zai-coding-cn", values);

export const ZAI_CODING_CN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/zai-coding-cn.json", { with: { type: "json" } }), "zai-coding-cn"> =
	flattenClassifierModelCatalog("zai-coding-cn", values);
