// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, flattenClassifierModelCatalog, type ChatModelCatalog, type ImageModelCatalog, type ClassifierModelCatalog } from "../model-catalog.ts";

export const ZAI_MODELS: ChatModelCatalog<typeof import("./data/zai.json", { with: { type: "json" } }), "zai"> =
	flattenChatModelCatalog("zai", values);

export const ZAI_IMAGE_MODELS: ImageModelCatalog<typeof import("./data/zai.json", { with: { type: "json" } }), "zai"> =
	flattenImageModelCatalog("zai", values);

export const ZAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof import("./data/zai.json", { with: { type: "json" } }), "zai"> =
	flattenClassifierModelCatalog("zai", values);
